apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: borrowdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: borrowdb
spec:
  selector:
    app: borrowdb
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrowdb
spec:
  selector:
    matchLabels:
      app: borrowdb
  template:
    metadata:
      labels:
        app: borrowdb
    spec:
      containers:
        - name: borrowdb
          image: fensan/coe692:borrowdb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: storage
              mountPath: /data/borrowdb
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: borrowdb-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrowbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrowbook
  template:
    metadata:
      labels:
        app: borrowbook
    spec:
      containers:
        - name: borrowbook
          image: fensan/coe692:borrowWebApp
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: borrowdb:3306
            - name: kubeMQAddress
              value: 10.24.14.133:50000
          imagePullPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: holddb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: holddb
spec:
  selector:
    app: holddb
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: holddb
spec:
  selector:
    matchLabels:
      app: holddb
  template:
    metadata:
      labels:
        app: holddb
    spec:
      containers:
        - name: holddb
          image: fensan/coe692:holddb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: storage
              mountPath: /data/holddb
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: holddb-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: holdbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: holdbook
  template:
    metadata:
      labels:
        app: holdbook
    spec:
      containers:
        - name: holdbook
          image: fensan/coe692:holdWebApp
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: holddb:3306
            - name: kubeMQAddress
              value: 10.24.14.133:50000
          imagePullPolicy: Always
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searchdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: searchdb
spec:
  selector:
    app: searchdb
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchdb
spec:
  selector:
    matchLabels:
      app: searchdb
  template:
    metadata:
      labels:
        app: searchdb
    spec:
      containers:
        - name: searchdb
          image: fensan/coe692:searchdb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: storage
              mountPath: /data/searchdb
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: searchdb-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchbook
  template:
    metadata:
      labels:
        app: searchbook
    spec:
      containers:
        - name: searchbook
          image: fensan/coe692:searchWebApp
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: searchdb:3306
            - name: kubeMQAddress
              value: 10.24.14.133:50000
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: fensan/coe692:frontendWebApp
          ports:
            - containerPort: 8080
          env:
            - name: searchService
              value: searchbook:80

            - name: holdService
              value: holdbook:80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: borrowbook
spec:
  selector:
    app: borrowbook
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: holdbook
spec:
  selector:
    app: holdbook
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: searchbook
spec:
  selector:
    app: searchbook
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer